# Generated by Django 3.2.12 on 2024-02-26 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_custompermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(to='users.CustomPermissions'),
        ),
    ]
